title: 15M Social Movement
url: https://www.15m.sg
favicon: /images/15M_socials.png
colors:
  primary-color: "#2266ff"
  secondary-color: "#2266ff"
  media-colors:
    - title: media-color-one
      color: "#f26052"
    - title: media-color-two
      color: "#a4c9ff"
    - title: media-color-three
      color: "#b4b1fe"
    - title: media-color-four
      color: "#ff991f"
    - title: media-color-five
      color: "#3dbccd"
description: Adding 15 million years of healthy life social movement
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d3j6kirispxood.amplifyapp.com
prod: https://master.duc5no27e7dwy.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Asset_8.png
is_government: false
google_analytics_ga4: G-XDQVWF4HHY
linkedin-insights: ""
resources_name: stories
